[install]
is_configured = 0
state = enabled
build = 3

[package]
id = TA-syncgitmdsearch

[ui]
is_visible = 1
label = Git Markdown Search Sync
setup_view = git_setup

[launcher]
author = TA-syncgitmdsearch
description = Fetch Markdown from Git, extract SPL, and save it as Splunk saved searches.
version = 1.0.0

[id]
name = TA-syncgitmdsearch
version = 1.0.0
