[admin:syncgitmdsearch]
match = /
members = syncgitmdsearch_settings

[admin_external:syncgitmdsearch_settings]
handlertype = python
python.version = python3
handlerfile = ta_syncgitmdsearch_rh_settings.py
handleractions = list, edit, create
handlerpersistentmode = true
capability = admin_all_objects
