[git]
repo_url =
branch = main
md_glob = **/*.md
auth_type = https_token
username =
target_app = search
target_owner = nobody
overwrite = false
verify_ssl = true
ssh_strict_host_key = true
git_command = git
skip_files = README.md,CONTRIBUTING.md,CHANGELOG.md,LICENSE.md
