[git]
repo_url =
branch = main
md_glob = **/*.md
provider = auto
api_base_url =
auth_type = https_token
username =
target_app = TA-syncgitmdsearch
target_owner = nobody
overwrite = false
skip_files = README.md,CONTRIBUTING.md,CHANGELOG.md,LICENSE.md
