[expose:syncgitmdsearch_settings]
pattern = syncgitmdsearch_settings
methods = GET, POST

[expose:syncgitmdsearch_settings_specified]
pattern = syncgitmdsearch_settings/*
methods = GET, POST, PUT, DELETE
